### ISSUE TITLE
"avr-g++: command not found" fix not work

### ISSUE THREAD

**Issue by Super169** [gepd/Stino#4]
I just try the following command in Sublime Text Console

  setx path "%path%;E:\Arduino\IDE\arduino-1.6.4"

where E:\Arduino\IDE\arduino-1.6.4 is the installation folder of Arduino IDE.

But the following error is returned:

```
setx path "%path%;E:\Arduino\IDE\arduino-1.6.4"
File "", line 1
setx path "%path%;E:\Arduino\IDE\arduino-1.6.4"
^
SyntaxError: invalid syntax
```

Is this command for the Console of Sublime Text 3?

Then I just try to create a batch file to set the path before running sublime text 3:
    setx path "%path%;E:\Arduino\IDE\arduino-1.6.4"
    "C:\Program Files\Sublime Text 3\subl.exe"

It can now start compile without error, but it will stop at [  3%] and no more progress.

The workstation has been reinstalled, so it should not be affected by other package, and I cannot use Sublime Text + Stino now.  Please help.

Thanks a lot.

**Comment by FrozenSUSHI** [comment]
If you are using Windows (tested on 7 and 8.1) you can add the direct path to the avr tools to your system's PATH variable and everything should work.
For example "Q:\Tools\arduino-1.6.5-r2\hardware\tools\avr\bin" ...

**Comment by ivanNair** [comment]
Please can you explain how you set the above to text line 3 im using windows 8 and have been try for the last few days to get it to work, i have tried the setx path "%path%;E:\Arduino\IDE\arduino-1.6.4"
also does not work. i have reloaded subline.
Can you please help

**Comment by clemler** [comment]
Thank you FrozenSUSHI - just the tip I needed. Ivan, I add the following to my path (this is a Mac, but the  core concept still applies):

/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin

On your PC, look at the sub-directories under arduino-1.6.4, per Frozen, it is likely under
E:\Arduino\IDE\arduino-1.6.4\hardware\tools\avr\bin

**Comment by Super169** [comment]
Thanks all, the problem is solved.  It has to update the path in Environment Variables.

**Comment by ivanNair** [comment]
hi guys 
I am dump struk now how does this work, i found the folder,avr.bin, but how to set path?
Pleeeeeease explain. im half blind at 
this stage 
Thank you

**Comment by ivanNair** [comment]
hi , after trying again i get
Package Control: Skipping automatic upgrade, last run at 2015-07-13 18:22:14, next run at 2015-07-13 19:22:14 or after

> > > "%path%;E:\Arduino\IDE\arduino-1.6.5-2"
> > > '%path%;E:\Arduino\IDE\x07rduino-1.6.5-2'
> > > "%path%;Q:\Arduino\IDE\arduino-1.6.5-r2"
> > > '%path%;Q:\Arduino\IDE\x07rduino-1.6.5-r2'

**Comment by ivanNair** [comment]
hi Clemler
i still cant get it right suline t3 and ardunio, on my pc i have to c then doc(x86) Arduino;hardware;avr;
and i get bin. in tere i can see the folder " avr-g++ What do i do next,
Please help if i click on the folder it opens to small black screen then closes

**Comment by kyleding** [comment]
"avr-gcc" -w -Os -Wl,--gc-sections -mmcu=atmega328p  -o "D:\arduino-nightly\DigitalReadSerial/sketch/DigitalReadSerial.elf" "D:\arduino-nightly\DigitalReadSerial\DigitalReadSerial.ino.cpp.o" "D:\arduino-nightly\DigitalReadSerial/core.a" "-LD:\arduino-nightly\DigitalReadSerial" -lm
d:/arduino-nightly/hardware/tools/avr/bin/../lib/gcc/avr/4.8.1/../../../../avr/bin/ld.exe: cannot open output file D:/arduino-nightly/DigitalReadSerial/sketch/DigitalReadSerial.elf: No such file or directory

this command is error:   -o "D:\arduino-nightly\DigitalReadSerial/sketch/DigitalReadSerial.elf" ,I'm in WINDOWS 7,so the path in windows "path separator" is use "\",but at the when I create elf,I found stino use "/".

I'm a beginner of Arduino and stino,So how can I fix the issue?

**Comment by gepd** [comment]
I've been merge a fix base on https://github.com/Robot-Will/Stino/issues/271 please download and test it.
